language: java
jdk:
  - oraclejdk7
  - openjdk7
install:
  - cat /proc/meminfo
  - cat /proc/cpuinfo
  - dpkg --get-selections
  - export STUCCO_DB_TYPE=INMEMORY
  - export STUCCO_DB_CONFIG='./config/inmemory.yml'
after_success:
  - wget https://raw.githubusercontent.com/stucco/test/master/rerun-test.sh
  - chmod a+x ./rerun-test.sh
  - ./rerun-test.sh
  - ./stop-test-server.sh
