language: java
jdk:
  - oraclejdk7
  - openjdk7
services:
  - elasticsearch
install:
  - wget https://raw.githubusercontent.com/stucco/test/master/scripts/install-titan.sh
  - chmod a+x ./install-titan.sh
  - sudo ./scripts/install-titan.sh 0.4.4 localhost
after_success:
  - wget https://raw.githubusercontent.com/stucco/test/master/rerun-test.sh
  - chmod a+x ./rerun-test.sh
  - ./rerun-test.sh