language: java
jdk:
  - oraclejdk7
  - openjdk7
install:
  - cat /proc/meminfo
  - cat /proc/cpuinfo
  - dpkg --get-selections
  - export STUCCO_DB_TYPE=INMEMORY
  - export STUCCO_DB_CONFIG='./config/inmemory.yml'
  - mvn -q --non-recursive scm:checkout -Dmodule.name=graph-db-connection
  - cd graph-db-connection
  - mvn -e clean install -Dmaven.test.skip=true
  - cd ..
after_success:
  - wget https://raw.githubusercontent.com/stucco/test/master/rerun-test.sh
  - chmod a+x ./rerun-test.sh
  - ./rerun-test.sh
  - ./stop-test-server.sh
